### ISSUE TITLE
mqtt sensor not working

### ISSUE THREAD

**Issue by milandzuris** [hjelev/rpi-mqtt-monitor#10]
![image](https://user-images.githubusercontent.com/42905545/192026377-54b3a551-5691-42a8-a258-62d79ffc3897.png)
mqtt sensors not working, in mqtt explorer i see sensors.

**Comment by hjelev** [comment]
do you get some error when you try to run the script?

**Comment by milandzuris** [comment]
Logger: homeassistant.components.mqtt.discovery
Source: components/mqtt/discovery.py:108
Integration: MQTT (documentation, issues)
First occurred: 19:37:05 (648 occurrences)
Last logged: 20:57:11

Received message on illegal discovery topic 'homeassistant/sensor/Dzuriš DNS Server/DzurisDNSServer_voltage/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/Dzuriš DNS Server/DzurisDNSServer_swap/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/Dzuriš DNS Server/DzurisDNSServer_memory/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/Dzuriš DNS Server/DzurisDNSServer_sys_clock_speed/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/Dzuriš DNS Server/DzurisDNSServer_uptime_days/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic

@hjelev

**Comment by hjelev** [comment]
Its that special char in your topic.
Check the error message. - The topic contains not allowed characters.
