### ISSUE TITLE
Illegal discovery topic

### ISSUE THREAD

**Issue by ahti123** [hjelev/rpi-mqtt-monitor#104]
rpi-monitor uses full hostname for the device name but according to the linked documentation, object_id (device) can contain only [a-zA-Z0-9_-]
--
[homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/rpi-MQTT-monitor/some.hostname.com_uptime_days/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/integrations/mqtt/#discovery-topic
--

**Comment by hjelev** [comment]
Thanks, I have merged your PR
