### ISSUE TITLE
Minor typo in documentation

### ISSUE THREAD

**Issue by julianlawson** [hjelev/rpi-mqtt-monitor#107]
The service examples in the Readme reference a service file called `rpi-cpu2mqtt.service`, however the filename in the distribution seems to have been changed to `rpi-mqtt-monitor.service`

Examples should read
`
sudo cp rpi-mqtt-monitor.service /etc/systemd/system/ ;
sudo systemctl enable rpi-mqtt-monitor.service
`
and
`
sudo service rpi-mqtt-monitor start ;
sudo service rpi-mqtt-monitor status
`
respectively

**Comment by hjelev** [comment]
Thank you, its updated now.
