### ISSUE TITLE
Feature Request: Monitor RSSI (WiFi Signal level)

### ISSUE THREAD

**Issue by maorcc** [hjelev/rpi-mqtt-monitor#12]
Is it possible to also monitor the RSSI (WiFi Signal level)?

**Comment by hjelev** [comment]
its a very good idea, I have created a branch called wifi and push it there. 
If you wish you can help me test it.

**Comment by maorcc** [comment]
Seems to work well.  Very nice! See below.
I'm used to **dBm** units.  I guess I can get used to signal in percentage. 
Is it possible to add the dBm value as an attribute of the `wifi_signal` entity?

![image](https://user-images.githubusercontent.com/255973/202817232-9a0d099b-6e59-4faa-b90c-bd3b0c4b0412.png)

**Comment by hjelev** [comment]
Nice, is it working when called with a cronjob?
 I can't get it to work when scheduled.

**Comment by hjelev** [comment]
I have added wifi signal in dBm.
you'll need to add wifi_signal_dbm = True to your config

**Comment by maorcc** [comment]
@hjelev, If I add to the config file both `wifi_signal_dbm` and `wifi_signal`, then in Home Assistant two entities are created with the following IDs:
- sensor.garden_wifi_signal
- sensor.garden_wifi_signal_2

Where both have the same name `Wifi Signal`.  This is somewhat confusing.

**Comment by maorcc** [comment]
Also, don't forget to update the READM.md with the new setting.

**Comment by maorcc** [comment]
And yes, the two wifi fields don't seem to work from crontab.  Maybe a permission issue?

**Comment by maorcc** [comment]
Regarding the crontab issue. It is resolved for me when I replaced lines 22 and 33 from:
```
full_cmd = "iwconfig wlan0 | grep -i --color quality"
```
to this:
```
full_cmd = "/sbin/iwconfig wlan0 | grep -i quality"
```
Using full path to the `iwconfig` tool.  (and removing the unneeded `--color` flag.)

**Comment by hjelev** [comment]
Thank for fixing the cron tab issue - I have forgotten about paths in cron tabs.
Regarding the duplicated name I made it like this on purpose as I don't think somebody will need both values. And to differentiate it them I have to name them Wifi Signal % and Wifi Signal dBm which won't look very good. If you have a better suggestion for the naming pls let me know. The cron fix is applied to wifi branch.

**Comment by maorcc** [comment]
I see your point regarding naming the "Wifi Signal".  I don't have a better name.

**Comment by hjelev** [comment]
wifi branch is merged to master
