### ISSUE TITLE
Feature request: more information about disk

### ISSUE THREAD

**Issue by AQU4R1U5** [hjelev/rpi-mqtt-monitor#128]
Hello and thank you for this wonderful project.

In my case I use it for my Raspberry Pi 4 with a USB M.2 SSD adapter.
Unfortunately, the hard drive in my setup seems to get quite hot, so I would be interested to know how hot.

Would this be possible?

You could also include further information, such as utilisation or a general indicator for the size of the hard drive.

This could also be interesting with the new Raspberry Pi 5, which supports PCIe and therefore allows even more hard drives to be connected to the Pi via PCIe.

**Comment by hjelev** [comment]
I have added a feature to display disk temperatures in v 0.9.4
you need to manually edit  config.py file after update as its disabled by default
Please test it and let me know if this is what you needed.

**Comment by AQU4R1U5** [comment]
Hi, thanks.

I activated the feature in my config:
<img width="121" alt="image" src="https://github.com/user-attachments/assets/a95edc94-9b57-4e17-bfdc-d1f677e1d06f">

But didn't get a output for the MQTT
<img width="352" alt="image" src="https://github.com/user-attachments/assets/9849cae9-2ddc-4977-b841-7d3d6b6388ec">

Do have a idea, what I could done wrong?

Thanks for your help

**Comment by hjelev** [comment]
show me the output of this command pls:
```
for hwmon in /sys/class/hwmon/hwmon*/name; do
  echo "Device: $(cat $hwmon)"
done
```

**Comment by AQU4R1U5** [comment]
Output: 
`
Device: cpu_thermal
Device: rpi_volt
`

**Comment by hjelev** [comment]
Unfortunately there is no information about the disk temperature in your system
