### ISSUE TITLE
Showing Firmware and Hardware on a card.

### ISSUE THREAD

**Issue by systempal** [hjelev/rpi-mqtt-monitor#131]
Actually the mqtt device show:

Informazioni Dispositivo
RPi MQTT Monitor 0.9.3
da github.com/hjelev
Firmware: Debian GNU/Linux 12 (bookworm)
Hardware: Raspberry Pi 5 Model B Rev 1.0 by Raspberry Pi

is there a way to display those informations on a card ?

**Comment by hjelev** [comment]
I was unable to find a way to display this as a card
