### ISSUE TITLE
Adding decimal digits on the CPU Temp Sensor

### ISSUE THREAD

**Issue by albeedelacruz** [hjelev/rpi-mqtt-monitor#132]
Is it possible to measure the CPU temperature down to last 2 decimal digits (ex: 50.42) instead of just whole numbers?

**Comment by hjelev** [comment]
On what system are you using the monitor?
For me under rpi OS it shows one digit after the floating point when under Ubuntu it only shows the whole number.

**Comment by albeedelacruz** [comment]
> On what system are you using the monitor? For me under rpi OS it shows one digit after the floating point when under Ubuntu it only shows the whole number.

Hi, I am passing the data from this to Home Assistant
![image](https://github.com/user-attachments/assets/35bb905c-fdb9-4c7e-a8ff-c83922a9f942)
