### ISSUE TITLE
Feature request: Power Supply Checker

### ISSUE THREAD

**Issue by WarC0zes** [hjelev/rpi-mqtt-monitor#138]
Hi,
Would it be possible to add a power supply checker for the RPI ?

Be informed if there's undervoltage on the RPI, like Raspberry Pi Power Supply Checker integration:
https://www.home-assistant.io/integrations/rpi_power

**Comment by hjelev** [comment]
you have the option to monitor voltage = True - this will show you if you have power issues.

**Comment by WarC0zes** [comment]
I activated the sensor.
In the terminal, I had undervoltage messages, but saw nothing at the voltage sensor. 
![image](https://github.com/user-attachments/assets/c6ee7add-57c2-49c2-b58a-3678787df896)

This happened 6 days ago, the voltage sensor has not moved.
![image](https://github.com/user-attachments/assets/cc17e1e0-eff9-4140-88ce-1ca400008f08)

**Comment by hjelev** [comment]
hmm - ok I'll check how I can capture these under voltage signals on the rpi

**Comment by amse2000** [comment]
Maybe something like this will help:
It will join all "Messages" that are currently set. 
Maybe you can just check for Current "Under-Voltage" or "Under-Voltage since last reboot"
In my "Test-Code" there is just the display option, I didn't finish/prepare the mqtt transfer and so on,
but maybe it helps to implement "UnderVoltage-Messages"
 
def check_undervoltage():
    try:
        full_cmd = "vcgencmd get_throttled | cut -f2 -d= | sed 's/000//'"
        MESSAGES = {
            0: 'Under-voltage!',
            1: 'ARM frequency capped!',
            2: 'Currently throttled!',
            3: 'Soft temperature limit active',
            16: 'Under-voltage has occurred since last reboot.',
            17: 'Throttling has occurred since last reboot.',
            18: 'ARM frequency capped has occurred since last reboot.',
            19: 'Soft temperature limit has occurred'
        }

        throttled_output = subprocess.Popen(full_cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()[0]
        #throttled_output = 'throttled=0x5005' #simulate 0 and 16
        throttled_binary = bin(int(throttled_output, 0))

        messages = ""
        for position, message in MESSAGES.items():
          if len(throttled_binary) > position and throttled_binary[0 - position - 1] == '1':
              messages += message  + '\n'

    except Exception as e:
            messages = repr(e)

    return messages

**Comment by hjelev** [comment]
I have added a simple version of this sensor that displays OK if result is 0x0 and KO if result is different,
I am not sure how it will look in hass if I put the long translation of the error, maybe I'll test later and implement it if it don't look bad.

**Comment by WarC0zes** [comment]
Great :+1: 
thanks !
![image](https://github.com/user-attachments/assets/ad8820a5-e15b-4658-b0d6-451b945c6b74)
