### ISSUE TITLE
Addtional external sensors for RPi Environment

### ISSUE THREAD

**Issue by pallago** [hjelev/rpi-mqtt-monitor#143]
This monitor is awesome! I use the RPi monitor mostly on Rpi Zero, which is located on a self-made PCB with power supply in a housing.
Inside the housing there is a DS18B20 1-wire sensor checking the temperature inside (power supply and RPi) and outside the housing there is Sensirion SHT21 sensor connected or maybe in future a BME180 via I2C bus to measure the environment.

I would like to add the measured temperature, humidity (maybe pressure) and transmit these measurements via MQTT, in particular to integrate these values into the monitor.

I want to try to implement this feature within the next days/weeks. My question is about the structure. What do you think might be the best? An additional git branch for external sensors?
In python: a list including the type (like `ext_sensors=[DS18B20, SHT21]`) and addresses or IDs like (`ext_IDs=[0014531448ff, 0x40]`)?
How about libraries for the sensors? The DS18B20 is the easiest, I will write a few lines in order to read the text file (`/sys/bus/w1/devices/28-0014531448ff/w1_slave`).

Best regards!

**Comment by pallago** [comment]
If somebody is interested and willing to test some external sensors like DS18B20 or SHT21

https://github.com/pallago/rpi-mqtt-monitor/tree/ext_sensors

**Comment by hjelev** [comment]
Thank you pallago, merged your PR and tagged as version 0.11.0

**Comment by pallago** [comment]
Thank you for merging. But please also check (maybe before ;)) whether everything still works ;)
