### ISSUE TITLE
Probleme Temperature CPU

### ISSUE THREAD

**Issue by gael1980** [hjelev/rpi-mqtt-monitor#144]
Bonjour,
Depuis la dernière mise à jour du script, j'ai les température ne remonte plus.
Voici le message d'erreur remonté par Home assistant : 

ValueError: Sensor sensor.dietpi_mqtt_cpu_temperature_2 has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '40,78' ()

Merci

Gaël

**Comment by hendrikwolf79** [comment]
I have the same problem. The reason for the error is the decimal separator. HA need point and not comma.

**Comment by hjelev** [comment]
A fix for this is added to master branch.
