### ISSUE TITLE
auth could not identify password

### ISSUE THREAD

**Issue by duceduc** [hjelev/rpi-mqtt-monitor#154]
Hello. I am seeing this error/warning  with rpi-mqtt-monitor v 0.10.1. Previous version did not have this error.

    ser@ser:/srv/git/rpi-mqtt-monitor/src$ sudo systemctl status rpi-mqtt-monitor.service
    ● rpi-mqtt-monitor.service - System Sensors Monitor
         Loaded: loaded (/etc/systemd/system/rpi-mqtt-monitor.service; enabled; vendor preset: enabled)
         Active: active (running) since Mon 2024-11-04 10:18:23 JST; 2min 6s ago
       Main PID: 2208852 (python3)
          Tasks: 4 (limit: 15308)
         Memory: 23.7M
            CPU: 387ms
         CGroup: /system.slice/rpi-mqtt-monitor.service
                 └─2208852 /usr/bin/python3 /srv/git/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py --service

    Nov 04 10:18:23 ser systemd[1]: Started System Sensors Monitor.
    Nov 04 10:18:23 ser sudo[2208870]: pam_unix(sudo:auth): conversation failed
    Nov 04 10:18:23 ser sudo[2208870]: pam_unix(sudo:auth): auth could not identify password for [ser]

For another install on different machine, I see this warning.

    ngx@ngx:/srv/git/rpi-mqtt-monitor/src $  sudo systemctl status rpi-mqtt-monitor.service
    ● rpi-mqtt-monitor.service - System Sensors Monitor
         Loaded: loaded (/etc/systemd/system/rpi-mqtt-monitor.service; enabled; preset: enabled)
         Active: active (running) since Mon 2024-11-04 07:02:15 JST; 3h 25min ago
       Main PID: 2667063 (python3)
          Tasks: 4 (limit: 8738)
            CPU: 1min 43.516s
         CGroup: /system.slice/rpi-mqtt-monitor.service
                 └─2667063 /usr/bin/python3 /srv/git/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py --service

    Nov 04 07:02:26 ngx sudo[2667082]: pam_unix(sudo:session): session closed for user root
    Nov 04 08:02:37 ngx sudo[2807734]:      ngx : PWD=/srv/git/rpi-mqtt-monitor ; USER=root ; COMMAND=/usr/bin/apt update
    Nov 04 08:02:37 ngx sudo[2807734]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
    Nov 04 08:02:47 ngx sudo[2807734]: pam_unix(sudo:session): session closed for user root
    Nov 04 09:02:58 ngx sudo[2950568]:      ngx : PWD=/srv/git/rpi-mqtt-monitor ; USER=root ; COMMAND=/usr/bin/apt update
    Nov 04 09:02:58 ngx sudo[2950568]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
    Nov 04 09:03:10 ngx sudo[2950568]: pam_unix(sudo:session): session closed for user root
    Nov 04 10:03:19 ngx sudo[3098886]:      ngx : PWD=/srv/git/rpi-mqtt-monitor ; USER=root ; COMMAND=/usr/bin/apt update
    Nov 04 10:03:19 ngx sudo[3098886]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
    Nov 04 10:03:34 ngx sudo[3098886]: pam_unix(sudo:session): session closed for user root

**Comment by hjelev** [comment]
From what I see in your first installation your service is not running with root user - if you want to use the options to restart your system, (not 100% sure but maybe the update via hass also needs root)  you need to run the service as root.
You can check how you run your service  - the file is located here /etc/systemd/system/rpi-mqtt-monitor.service
check the line saying User=, change the user to root and restart the service, the error/warning should stop.

**Comment by duceduc** [comment]
Hi. Both the machines are not set to user=root yet the first installation shows different error message then the second installation. 

I've changed the first installation to user=root and the error message is the same as the second installation now or is it just a log message??

**Comment by hjelev** [comment]
second one is just a log message, its fine.
