### ISSUE TITLE
how to update link in main README does not work

### ISSUE THREAD

**Issue by f18m** [hjelev/rpi-mqtt-monitor#171]

**Comment by hjelev** [comment]
What is the error message you get?

**Comment by f18m** [comment]
My bad sorry: I meant to say that in the README file https://raw.githubusercontent.com/hjelev/rpi-mqtt-monitor/refs/heads/master/README.md there is a hand-written TOC which contains invalid entries like "How To update" and "Schedule ..." entries

**Comment by hjelev** [comment]
thanks I see the issue - will fix it

**Comment by hjelev** [comment]
The links are working now
