### ISSUE TITLE
Unable to get it work on Ubuntu Server

### ISSUE THREAD

**Issue by P-Stenbumling** [hjelev/rpi-mqtt-monitor#18]
Linux raspberrypi4 5.19.0-1009-raspi #16-Ubuntu SMP PREEMPT Thu Nov 24 13:38:20 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

``pi@raspberrypi4:~/rpi-mqtt-monitor/src$ /usr/bin/python3 /home/pi/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
Traceback (most recent call last):
  File "/home/pi/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py", line 318, in <module>
    swap = check_swap()
  File "/home/pi/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py", line 71, in check_swap
    swap = round(float(swap.decode("utf-8").replace(",", ".")), 1)
ValueError: could not convert string to float: ''

**Comment by ezhische** [comment]
Can you exicute from console and post the output:
free -t |grep -i swap | awk 'NR == 1 {print $3/$2*100}'

**Comment by olexs** [comment]
Set the following in your `config.py`:

```python
sys_clock_speed = False
swap = False
```

The code for those measurements is RaspberryPi-specific and doesn't work on other systems. With those two disabled, I run the monitor on multiple VPS's with Ubuntu Server with no issues.

**Comment by hjelev** [comment]
I have updated the script and now both wifi, swap and sys_clock_speed are also working on Ubuntu.
