### ISSUE TITLE
check_cpu_load can't parse float

### ISSUE THREAD

**Issue by JcDenis** [hjelev/rpi-mqtt-monitor#2]
I don't know if it is because I use FR locales but check_cpu_load won't work as it should.
**Uptime** returns **0,91** instead of **0.91**

To fix it, change line 27 from this :
`cpu_load = p.split("average:")[1].split(",")[0].replace(' ', '')`
to that to change "," in "." :
`cpu_load = p.split("average:")[1].split(", ")[0].replace(' ', '').replace(',', '.')`

**Comment by hjelev** [comment]
I have added your suggestion to the code as it doesn't heart the other cases where there is no , in the cpu load value
