### ISSUE TITLE
Feature Request: Restart Button

### ISSUE THREAD

**Issue by CFenner** [hjelev/rpi-mqtt-monitor#29]
A restart button that can restart the RPi on demand.

**Comment by hjelev** [comment]
This is not planned for this script, but I am working on another one which currently have shut-down and monitor control, will add restart functionality and update the readme next time I work on it https://github.com/hjelev/web-shutdown

**Comment by hjelev** [comment]
It was not planned but is now possible as the script subscribes to a topic and listens for update command

**Comment by hjelev** [comment]
This is implemented in version 0.8
Planning to add on/off button (on via wake on lan)
