### ISSUE TITLE
Feature Request: Update Entity

### ISSUE THREAD

**Issue by CFenner** [hjelev/rpi-mqtt-monitor#30]
A update entity that makes use of #28 to display when there are changes and enabled a remote update.

**Comment by hjelev** [comment]
How do you imagine this remote update?
I have updated the script to support update but not sure how to trigger the update via hass, most probably via mqtt message but still thinking about it. If you have some ideas I'll be happy to hear them.

**Comment by CFenner** [comment]
I know that https://github.com/tbnobody/OpenDTU uses also MQTT and is able to receive commands. No idea if there is a Mqtt server running or how the communication back is working.

**Comment by hjelev** [comment]
Thanks, I'll look into this. This is a very nice feature to have.

**Comment by hjelev** [comment]
I believe I've successfully implemented the remote updates through Home Assistant. To test this, please follow these steps:

1. Update your local repository by running `git pull`.
2. Execute the update script with `python3 src/update.py`.

Please note, you may encounter an error if there are missing variables in your `config.py` file. If this happens, refer to `config.py.example` and add the necessary variables to your `config.py` file.

Once updated, everything should operate smoothly in the upcoming updates.

**Comment by CFenner** [comment]
Looks nice, I could not test it though. Simply reverting on commit seems not to work to mimic an update available.

**Comment by hjelev** [comment]
Yes revering commit don't trigger the update, I am checking local and
remote tag and if there is a difference update is active when I push the
next update you'll be able to test it.

**Comment by CFenner** [comment]
Update popped up 👍 

But it's showing the new version two times?!

<img width="675" alt="Bildschirmfoto 2024-02-01 um 16 23 07" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/136a2b6d-33f6-4a23-aabd-c03583b58109">

Also when clicking update, there is not feedback. Window stays open and not "installing" or something else visible.

**Comment by hjelev** [comment]
I have noticed the version duplication and fixed that.
Was the update successfull. I don't know how to provide feedback to hass regarding update status but for me it takes couple of seconds and the versions sync, status changes to up to date ... not perfect but the update is done

**Comment by CFenner** [comment]
Updating from 0.7.2 did not work. I updated now to 0.7.6 locally. Let's see how the next release goes.

**Comment by hjelev** [comment]
I have separated the update system in another thread so i can only check for updates once per hour or as configured and this broke the update  system, version 0.6.10 fixes it, hope I don't break it anymore.

**Comment by CFenner** [comment]
<img width="381" alt="Bildschirmfoto 2024-02-02 um 08 31 30" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/3257706d-9b01-47d6-b6da-5e9cff7b4a0c">

There is something going on with the verisions.

**Comment by hjelev** [comment]
I was fixing the update until late night and got it messed - fixed the release page and hope the  update system is stable now.
Now it should be possible to check for updates every hour or so not each time you send measurements to hass

**Comment by hjelev** [comment]
should work fine now
