### ISSUE TITLE
Issue with update & git changes

### ISSUE THREAD

**Issue by CFenner** [hjelev/rpi-mqtt-monitor#69]
When there are changes in the local git and the code cannot be updated, the update script now succeeds.

<img width="628" alt="Bildschirmfoto 2024-02-02 um 08 54 35" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/a8340a10-e116-4451-9e7f-854608982445">

**Comment by hjelev** [comment]
i know that if there are changes in the repo the update won't work. I can fix this by stashing all changes but this might not be perfect for somebody, else if you only update your config.py your repo is in updatable state.

**Comment by hjelev** [comment]
I think the update works fine now.
my devices updated all fine.
How was on your end?

**Comment by CFenner** [comment]
No, not really.
Looks like my config is not really handled correctly. I enable update sensor and uptime seconds but nothing is showing up. Really weird.

**Comment by CFenner** [comment]
For some reason the fan topic is reported as `False`

<img width="216" alt="Bildschirmfoto 2024-02-05 um 22 49 59" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/6deaa988-d9dd-4d10-8c96-ab7ffc12e744">

Shouldn't this be `0` or not be there at all?

**Comment by hjelev** [comment]
The issue with the git and update should be resolved now, but you need to reinstall as there are changes to the service file + one additional git command during installation to allow root to read the repository. You are right in your last comment that I am sending disabled values, will dig into this now

**Comment by CFenner** [comment]
What is the best way to uninstall and make sure there is no process running anymore? When I did changes in the past to the script and ran it more often, I had the feeling the old script was running somewhere in the background.

**Comment by CFenner** [comment]
Just ran `--update` again and got this message.
<img width="545" alt="Bildschirmfoto 2024-02-11 um 18 34 32" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/751c1a6f-7e48-472d-9937-364295fea327">

But when running `--display` it's saying 

<img width="507" alt="Bildschirmfoto 2024-02-11 um 18 34 21" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/1118c35d-1791-452c-8e51-b80309d87166">

Where does this come from?

**Comment by CFenner** [comment]
Ok, I was not on `master` branch.

<img width="349" alt="Bildschirmfoto 2024-02-11 um 18 38 30" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/9207deff-675d-4d1a-8bed-8b5767754e4e">

**Comment by CFenner** [comment]
I now tried to use service instead of cron job. Let's see if that works better.

The 0.6.2 seems to come from here: https://github.com/hjelev/rpi-mqtt-monitor/blob/bc7ba4ec1c71e9f85afa1660e12e18b75f3706c3/src/config.py.example#L4

**Comment by CFenner** [comment]
Interesting, I reduced the `update_check_intervall` to `60` and now I get only the update sensor and binary sensor for updates available. Could it be that the scripts are blocking each other?!

**Comment by hjelev** [comment]
if you want to use the update and new  buttons you need to run the script as a service.
To uninstall:
-  delete or comment out your cron entry # crontab -e
- delete the folder where the script is installed
- run the install script again and pick service option
The version in the config.py.example is 0.6.2 I am not updateing it every time but when the script is installed or updated its automatically updated.
If you reinstall now as service and delete your cron entry all should be fine.
I'll leave this open since it looks you still have update problems

**Comment by CFenner** [comment]
I removed the folder and service and now it seems to work.
