### ISSUE TITLE
How to monitor externally mounted array

### ISSUE THREAD

**Issue by jbrepogmailcom** [hjelev/rpi-mqtt-monitor#8]
Hello, I use rpi as NAS and have raid0 array. How should I modify the .py script to display (or add mqtt message for) external storage?

/dev/md0 on /RAID3T

Thanks, Jan

**Comment by hjelev** [comment]
Hi, on this line of the code I set the path for the space check, try checking that:
https://github.com/hjelev/rpi-mqtt-monitor/blob/ac5d9927f28d788443963e89a19c788bc9d26609/src/rpi-cpu2mqtt.py#L243
