### ISSUE TITLE
Feature request: Connectivity sensor

### ISSUE THREAD

**Issue by CFenner** [hjelev/rpi-mqtt-monitor#89]
Use last will to implement a connectivity sensor.

https://eclipse.dev/paho/files/paho.mqtt.python/html/client.html#paho.mqtt.client.Client.will_set

<img width="331" alt="Bildschirmfoto 2024-02-13 um 21 44 45" src="https://github.com/hjelev/rpi-mqtt-monitor/assets/9592452/453a27b3-3731-42ad-aef1-442436ca1afb">

**Comment by silviu-social1st-ro** [comment]
Hello! A status sensor would be awesome!
I found your project while i was trying to improvise a bash script to update mqtt with info from another host.
I have multiple computers in my house and i would like to have them intergrated into HomeAssistant and also to be able to wake them over lan.
however, if i use default wake on lan switch from homeassistant, the machine is being waken by the homeassistant ping.
so i wanted to have the status in homeassistant via mqtt, not ping.

your script is very efficient and well built. could you add, please, a status sensor? and maybe an action to wake over lan? :D

thanks!
