### ISSUE TITLE
Feature request: IP address sensor

### ISSUE THREAD

**Issue by julianlawson** [hjelev/rpi-mqtt-monitor#96]
Hi, thanks for a fantastic tool. I realise it's pretty much static data, but it would be great if the monitor were able to send the ipv4 and/or ipv6 address of the pi via MQTT.

**Comment by hjelev** [comment]
Do you really need this? What is the use case?
Once you install rpi-mqtt-monitor you can run this python3 src/rpi-cpu2mqtt.py -d and get the ip address displayed

**Comment by hjelev** [comment]
![image](https://github.com/user-attachments/assets/a3985fa9-c85d-458a-be5e-8c1521b831f2)
Added the IP address in device info section.
